// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4919.TestRobot;

import org.usfirst.frc4919.TestRobot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc4919.TestRobot.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton shootButton;
    public JoystickButton setBrakeButton;
    public Joystick driveJoystick;
    public JoystickButton towerUpButton;
    public JoystickButton towerDownButton;
    public JoystickButton towerStopButton;
    public JoystickButton pickupButton;
    public JoystickButton swapViewButton;
    public Joystick towerJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        towerJoystick = new Joystick(1);
        
        swapViewButton = new JoystickButton(towerJoystick, 4);
        swapViewButton.whenPressed(new SwapView());
        pickupButton = new JoystickButton(towerJoystick, 4);
        pickupButton.whileHeld(new Pickuptheball());
        towerStopButton = new JoystickButton(towerJoystick, 3);
        towerStopButton.whenPressed(new TowerStop());
        towerDownButton = new JoystickButton(towerJoystick, 2);
        towerDownButton.whenPressed(new TowerDown());
        towerUpButton = new JoystickButton(towerJoystick, 1);
        towerUpButton.whenPressed(new TowerUp());
        driveJoystick = new Joystick(0);
        
        setBrakeButton = new JoystickButton(driveJoystick, 2);
        setBrakeButton.whileHeld(new SetBrake());
        shootButton = new JoystickButton(driveJoystick, 1);
        shootButton.whenPressed(new Shoot());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Drive With Joystick", new DriveWithJoystick());
        SmartDashboard.putData("Tower Up", new TowerUp());
        SmartDashboard.putData("Tower Down", new TowerDown());
        SmartDashboard.putData("Tower Stop", new TowerStop());
        SmartDashboard.putData("Shoot", new Shoot());
        SmartDashboard.putData("Pickup the ball", new Pickuptheball());
        SmartDashboard.putData("Set Brake", new SetBrake());
        SmartDashboard.putData("Swap View", new SwapView());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriveJoystick() {
        return driveJoystick;
    }

    public Joystick getTowerJoystick() {
        return towerJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

