// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4919.TestRobot.subsystems;

import org.usfirst.frc4919.TestRobot.RobotMap;
import org.usfirst.frc4919.TestRobot.commands.*;
import edu.wpi.first.wpilibj.AnalogAccelerometer;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Joystick;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drivetrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController left = RobotMap.drivetrainLeft;
    private final SpeedController right = RobotMap.drivetrainRight;
    private final RobotDrive tankDriveConfiguration = RobotMap.drivetrainTankDriveConfiguration;
    private final AnalogGyro analogGyro1 = RobotMap.drivetrainAnalogGyro1;
    private final AnalogInput ultrasonicSensor = RobotMap.drivetrainUltrasonicSensor;
    private final AnalogInput analogInput1 = RobotMap.drivetrainAnalogInput1;
    private final AnalogAccelerometer builtinAccelerometer = RobotMap.drivetrainBuiltinAccelerometer;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveWithJoystick());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void takeJoystickInputs(Joystick driveJoystick)
    {
    	tankDriveConfiguration.arcadeDrive(driveJoystick);
    }
    
    public void stop()
    {
    	tankDriveConfiguration.drive(0, 0);
    }
}

